#!/bin/bash
echo "This is MY swamp! Get out!"
#Set up variables
infile='data/co1.fa'
outfile='out.phy'
jobname='treee'
mu_maxiters=100

#Trim taxon names out of fasta header
cat $infile | awk -F " " '{if($2 ~ /[A-Za-z_0-9]/){print ">" $2}else{print $0}}' > trim.fa

wcin=$(cat trim.fa | wc -m)

./muscle -in trim.fa -phyiout $outfile -maxiters $mu_maxiters

wcout=$(cat $outfile | wc -m)

wcchange=$(expr $wcout - $wcin)

echo "Muscle added $wcchange characters.\n"


./raxml -f a -p 12345 -x 12345 -N 20 -s out.phy -m GTRCAT -n boot1 -T 2
./raxml -f b -t ref -z RAxML_bootstrap.boot1 -m GTRCAT -n consensus -T 2

echo "RAxML Finished!"
